{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Stat Panel",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Series Panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heatmap Panel",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg by (instance) (\r\n  rate(probe_duration_seconds{job=\"blackbox\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}